# Generated by Django 4.1.3 on 2022-11-13 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0007_tarefas"),
    ]

    operations = [
        migrations.DeleteModel(name="Tarefas",),
    ]
